// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARAYYIx5wZRnqU6LuoNuvppQNaGStJKvg',
    appId: '1:263592174867:web:a7894d86a0697f5dfc66e6',
    messagingSenderId: '263592174867',
    projectId: 'login-backend-c7cf6',
    authDomain: 'login-backend-c7cf6.firebaseapp.com',
    storageBucket: 'login-backend-c7cf6.firebasestorage.app',
    measurementId: 'G-F03506ZGTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJn-5Tlxa0tKVGH7ZvCWTyYUVEikEdt3c',
    appId: '1:263592174867:android:ed7d6a8308d9f412fc66e6',
    messagingSenderId: '263592174867',
    projectId: 'login-backend-c7cf6',
    storageBucket: 'login-backend-c7cf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuyknjJUrI46QLb9hJa0LXHF6akCv_3QU',
    appId: '1:263592174867:ios:e6519306ffd7c2b5fc66e6',
    messagingSenderId: '263592174867',
    projectId: 'login-backend-c7cf6',
    storageBucket: 'login-backend-c7cf6.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuyknjJUrI46QLb9hJa0LXHF6akCv_3QU',
    appId: '1:263592174867:ios:e6519306ffd7c2b5fc66e6',
    messagingSenderId: '263592174867',
    projectId: 'login-backend-c7cf6',
    storageBucket: 'login-backend-c7cf6.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARAYYIx5wZRnqU6LuoNuvppQNaGStJKvg',
    appId: '1:263592174867:web:b03ace62a065e218fc66e6',
    messagingSenderId: '263592174867',
    projectId: 'login-backend-c7cf6',
    authDomain: 'login-backend-c7cf6.firebaseapp.com',
    storageBucket: 'login-backend-c7cf6.firebasestorage.app',
    measurementId: 'G-C5MYB9S2Y7',
  );
}
